table Dim_Venues
	lineageTag: 58b7c9d3-e2f4-5a6b-7c8d-9e0f1a2b3c4d

	column VenueID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 1a1a2b3c-4d5e-6f7g-8h9i-0j1k2l3m4n5o
		summarizeBy: none
		sourceColumn: VenueID

		annotation SummarizationSetBy = Automatic

	column VenueName
		dataType: string
		lineageTag: 2b2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p
		summarizeBy: none
		sourceColumn: VenueName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 3c3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 4d4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 5e5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column PastShows
		dataType: int64
		formatString: 0
		lineageTag: 6f6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t
		summarizeBy: sum
		sourceColumn: PastShows

		annotation SummarizationSetBy = Automatic

	partition Dim_Venues = m
		mode: import
		source =
				let
					Source = PhishDataSource,
					Dim_Venues_Sheet = Source{[Item="Dim_Venues",Kind="Sheet"]}[Data],
					PromotedHeaders = Table.PromoteHeaders(Dim_Venues_Sheet, [PromoteAllScalars=true]),
					ChangedType = Table.TransformColumnTypes(PromotedHeaders,{
						{"VenueID", Int64.Type},
						{"VenueName", type text},
						{"City", type text},
						{"State", type text},
						{"Country", type text},
						{"PastShows", Int64.Type}
					})
				in
					ChangedType

	annotation PBI_ResultType = Table

