table Fact_Shows
	lineageTag: 47a6b8e2-d1c4-4d3a-9c8f-1e5a7b3d9f2a

	column ShowID
		dataType: int64
		formatString: 0
		lineageTag: 1a2b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6
		summarizeBy: none
		sourceColumn: ShowID

		annotation SummarizationSetBy = Automatic

	column ShowDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2b3c4d5e-6f7g-8h9i-0j1k-l2m3n4o5p6q7
		summarizeBy: none
		sourceColumn: ShowDate

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 3c4d5e6f-7g8h-9i0j-1k2l-m3n4o5p6q7r8
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column VenueID
		dataType: int64
		formatString: 0
		lineageTag: 4d5e6f7g-8h9i-0j1k-2l3m-n4o5p6q7r8s9
		summarizeBy: none
		sourceColumn: VenueID

		annotation SummarizationSetBy = Automatic

	column VenueName
		dataType: string
		lineageTag: 5e6f7g8h-9i0j-1k2l-3m4n-o5p6q7r8s9t0
		summarizeBy: none
		sourceColumn: VenueName

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 6f7g8h9i-0j1k-2l3m-4n5o-p6q7r8s9t0u1
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 7g8h9i0j-1k2l-3m4n-5o6p-q7r8s9t0u1v2
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 8h9i0j1k-2l3m-4n5o-6p7q-r8s9t0u1v2w3
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Artist
		dataType: string
		lineageTag: 9i0j1k2l-3m4n-5o6p-7q8r-s9t0u1v2w3x4
		summarizeBy: none
		sourceColumn: Artist

		annotation SummarizationSetBy = Automatic

	column TourName
		dataType: string
		lineageTag: 0j1k2l3m-4n5o-6p7q-8r9s-t0u1v2w3x4y5
		summarizeBy: none
		sourceColumn: TourName

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: double
		lineageTag: 1k2l3m4n-5o6p-7q8r-9s0t-u1v2w3x4y5z6
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReviewCount
		dataType: int64
		formatString: 0
		lineageTag: 2l3m4n5o-6p7q-8r9s-0t1u-v2w3x4y5z6a7
		summarizeBy: sum
		sourceColumn: ReviewCount

		annotation SummarizationSetBy = Automatic

	column Era
		dataType: string
		lineageTag: 3m4n5o6p-7q8r-9s0t-1u2v-w3x4y5z6a7b8
		summarizeBy: none
		sourceColumn: Era

		annotation SummarizationSetBy = Automatic

	partition Fact_Shows = m
		mode: import
		source =
				let
					Source = PhishDataSource,
					Fact_Shows_Sheet = Source{[Item="Fact_Shows",Kind="Sheet"]}[Data],
					PromotedHeaders = Table.PromoteHeaders(Fact_Shows_Sheet, [PromoteAllScalars=true]),
					ChangedType = Table.TransformColumnTypes(PromotedHeaders,{
						{"ShowID", Int64.Type},
						{"ShowDate", type datetime},
						{"Year", Int64.Type},
						{"VenueID", Int64.Type},
						{"VenueName", type text},
						{"City", type text},
						{"State", type text},
						{"Country", type text},
						{"Artist", type text},
						{"TourName", type text},
						{"Rating", type number},
						{"ReviewCount", Int64.Type},
						{"Era", type text}
					})
				in
					ChangedType

	annotation PBI_ResultType = Table

