table Top_50_Songs
	lineageTag: a3b2c8d9-e7f0-0a1b-2c3d-4e5f6a7b8c9d

	column SongID
		dataType: int64
		formatString: 0
		lineageTag: 1r1r2s3t-4u5v-6w7x-8y9z-0a1b2c3d4e5f
		summarizeBy: none
		sourceColumn: SongID

		annotation SummarizationSetBy = Automatic

	column SongName
		dataType: string
		lineageTag: 2s2s3t4u-5v6w-7x8y-9z0a-1b2c3d4e5f6g
		summarizeBy: none
		sourceColumn: SongName

		annotation SummarizationSetBy = Automatic

	column TimesPlayed
		dataType: int64
		formatString: 0
		lineageTag: 3t3t4u5v-6w7x-8y9z-0a1b-2c3d4e5f6g7h
		summarizeBy: sum
		sourceColumn: TimesPlayed

		annotation SummarizationSetBy = Automatic

	column Debut
		dataType: string
		lineageTag: c9982111-43af-44b6-b651-aa72cf70e024
		summarizeBy: none
		sourceColumn: Debut

		annotation SummarizationSetBy = Automatic

	column LastPlayed
		dataType: string
		lineageTag: b559ed6f-add7-4d24-bab2-9f48ee130536
		summarizeBy: none
		sourceColumn: LastPlayed

		annotation SummarizationSetBy = Automatic

	column Gap
		dataType: string
		lineageTag: 3a28a57c-570c-4c9b-9e77-70facb0abd09
		summarizeBy: none
		sourceColumn: Gap

		annotation SummarizationSetBy = Automatic

	partition Top_50_Songs = m
		mode: import
		source =
				let
					Source = PhishDataSource,
					Top_50_Songs_Sheet = Source{[Item="Top_50_Songs",Kind="Sheet"]}[Data],
					PromotedHeaders = Table.PromoteHeaders(Top_50_Songs_Sheet, [PromoteAllScalars=true]),
					ChangedType = Table.TransformColumnTypes(PromotedHeaders,{
						{"SongID", Int64.Type},
						{"SongName", type text},
						{"TimesPlayed", Int64.Type}
					})
				in
					ChangedType

	annotation PBI_ResultType = Table

